### ISSUE TITLE
When is the referee released?

### ISSUE THREAD

**Issue by huiwang** [KevinBusse/cg-referee-wondev-woman#2]
Hello @KevinBusse,  Do you release the referee during the game or after it? Thanks!

**Comment by kevinsandow** [comment]
I released it as soon as possible, generally 2-3 days into the contest

**Comment by huiwang** [comment]
That's great! 

Do you have a short guide explaining how to make the official referee cg-brutaltester compatible?

**Comment by kevinsandow** [comment]
Actually I only followed the instruction as mentioned here: https://github.com/dreignier/cg-brutaltester/
